In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
df_train = pd.read_csv("dataset/train.csv")
df_test = pd.read_csv("dataset/test.csv")

In [3]:
print(df_train.shape)
print(df_test.shape)

(77299, 11)
(41778, 10)

## Dataset Description

In [5]:
df_train.head()

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
0,0,qp02z1,48,0:0,0.048804,NaN,1,Not Allowed,No,NaN,NaN
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny
3,3,qp08gt,48,0:0,0.003272,Residential,1,Not Allowed,No,NaN,Rainy
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy

In [6]:
df_train.describe()

              Index           day        demand  NumberofLanes   Temperature
count  77299.000000  77299.000000  7.729900e+04   77299.000000  74804.000000
mean   38649.000000     48.101838  9.394238e-02       2.014334     16.405354
std    22314.443566      0.302438  1.421905e-01       0.904665      7.359835
min        0.000000     48.000000  6.245650e-07       1.000000    -14.935097
25%    19324.500000     48.000000  1.822723e-02       1.000000     11.430473
50%    38649.000000     48.000000  4.775994e-02       2.000000     16.382587
75%    57973.500000     48.000000  1.085951e-01       3.000000     21.298833
max    77298.000000     49.000000  1.000000e+00       5.000000     48.251433

In [7]:
df_train.dtypes

Index              int64
geohash           object
day                int64
timestamp         object
demand           float64
RoadType          object
NumberofLanes      int64
LargeVehicles     object
Landmarks         object
Temperature      float64
Weather           object
dtype: object

## Dataset Preprocessing

#### Removing NaN values

In [10]:
df_train.isna().sum()

Index               0
geohash             0
day                 0
timestamp           0
demand              0
RoadType          600
NumberofLanes       0
LargeVehicles       0
Landmarks           0
Temperature      2495
Weather           797
dtype: int64

In [11]:
numerical_cols = df_train.select_dtypes(include = ['int64','float64']).columns.tolist()

In [12]:
categorical_cols = df_train.select_dtypes(include = ['object']).columns.tolist()

In [13]:
print("Numerical:", numerical_cols)
print("Categorical:", categorical_cols)

Numerical: ['Index', 'day', 'demand', 'NumberofLanes', 'Temperature']
Categorical: ['geohash', 'timestamp', 'RoadType', 'LargeVehicles', 'Landmarks', 'Weather']

In [14]:
for col in numerical_cols:
    df_train[col] = df_train[col].fillna(df_train[col].median())

for col in categorical_cols:
    mode = df_train[col].mode()[0]
    df_train[col] = df_train[col].fillna(mode)

In [15]:
df_train.isna().sum()

Index            0
geohash          0
day              0
timestamp        0
demand           0
RoadType         0
NumberofLanes    0
LargeVehicles    0
Landmarks        0
Temperature      0
Weather          0
dtype: int64

#### Encoding

In [17]:
categorical_cols

['geohash', 'timestamp', 'RoadType', 'LargeVehicles', 'Landmarks', 'Weather']

In [18]:
for col in categorical_cols:
    print(col, ":", df_train[col].nunique())

geohash : 1249
timestamp : 96
RoadType : 3
LargeVehicles : 2
Landmarks : 2
Weather : 4

In [19]:
le = LabelEncoder()
le.fit(df_train['geohash'])
df_train['geohash'] = le.transform(df_train['geohash'])

In [20]:
df_train.head()

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
0,0,4,48,0:0,0.048804,Residential,1,Not Allowed,No,16.382587,Sunny
1,1,25,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny
2,2,370,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny
3,3,416,48,0:0,0.003272,Residential,1,Not Allowed,No,16.382587,Rainy
4,4,22,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy

In [21]:
df_train['timestamp'].unique()

array(['0:0', '0:15', '0:30', '0:45', '1:0', '1:15', '1:30', '1:45',
       '2:0', '2:15', '2:30', '2:45', '3:0', '3:15', '3:30', '3:45',
       '4:0', '4:15', '4:30', '4:45', '5:0', '5:15', '5:30', '5:45',
       '6:0', '6:15', '6:30', '6:45', '7:0', '7:15', '7:30', '7:45',
       '8:0', '8:15', '8:30', '8:45', '9:0', '9:15', '9:30', '9:45',
       '10:0', '10:15', '10:30', '10:45', '11:0', '11:15', '11:30',
       '11:45', '12:0', '12:15', '12:30', '12:45', '13:0', '13:15',
       '13:30', '13:45', '14:0', '14:15', '14:30', '14:45', '15:0',
       '15:15', '15:30', '15:45', '16:0', '16:15', '16:30', '16:45',
       '17:0', '17:15', '17:30', '17:45', '18:0', '18:15', '18:30',
       '18:45', '19:0', '19:15', '19:30', '19:45', '20:0', '20:15',
       '20:30', '20:45', '21:0', '21:15', '21:30', '21:45', '22:0',
       '22:15', '22:30', '22:45', '23:0', '23:15', '23:30', '23:45'],
      dtype=object)

In [22]:
ohe_cols = ['RoadType','Weather']

df_train = pd.get_dummies(
    df_train,
    columns=ohe_cols,
    dtype=int,
    drop_first=True
)
df_train.head()

,Index,geohash,day,timestamp,demand,NumberofLanes,LargeVehicles,Landmarks,Temperature,RoadType_Residential,RoadType_Street,Weather_Rainy,Weather_Snowy,Weather_Sunny
0,0,4,48,0:0,0.048804,1,Not Allowed,No,16.382587,1,0,0,0,1
1,1,25,48,0:0,0.118507,3,Allowed,Yes,31.104565,1,0,0,0,1
2,2,370,48,0:0,0.027132,1,Not Allowed,No,25.919267,1,0,0,0,1
3,3,416,48,0:0,0.003272,1,Not Allowed,No,16.382587,1,0,1,0,0
4,4,22,48,0:0,0.010819,1,Not Allowed,No,10.803667,1,0,1,0,0

In [23]:
df_train['LargeVehicles'] = df_train['LargeVehicles'].map({
    'Not Allowed': 0,
    'Allowed': 1
})

df_train['Landmarks'] = df_train['Landmarks'].map({
    'No': 0,
    'Yes': 1
})

In [24]:
df_train.head()

,Index,geohash,day,timestamp,demand,NumberofLanes,LargeVehicles,Landmarks,Temperature,RoadType_Residential,RoadType_Street,Weather_Rainy,Weather_Snowy,Weather_Sunny
0,0,4,48,0:0,0.048804,1,0,0,16.382587,1,0,0,0,1
1,1,25,48,0:0,0.118507,3,1,1,31.104565,1,0,0,0,1
2,2,370,48,0:0,0.027132,1,0,0,25.919267,1,0,0,0,1
3,3,416,48,0:0,0.003272,1,0,0,16.382587,1,0,1,0,0
4,4,22,48,0:0,0.010819,1,0,0,10.803667,1,0,1,0,0

In [25]:
df_train.columns

Index(['Index', 'geohash', 'day', 'timestamp', 'demand', 'NumberofLanes',
       'LargeVehicles', 'Landmarks', 'Temperature', 'RoadType_Residential',
       'RoadType_Street', 'Weather_Rainy', 'Weather_Snowy', 'Weather_Sunny'],
      dtype='object')

#### Convert time stamp to individual features hour and minutes

In [27]:
split = df_train['timestamp'].str.split(':',expand=True)
df_train['hour'] = split[0].astype(int)
df_train['minute'] = split[1].astype(int)

df_train.drop('timestamp', axis=1, inplace=True)

In [28]:
df_train[['hour','minute']].nunique()

hour      24
minute     4
dtype: int64

In [55]:
df_train.describe()

,Index,geohash,day,demand,NumberofLanes,LargeVehicles,Landmarks,Temperature,RoadType_Residential,RoadType_Street,Weather_Rainy,Weather_Snowy,Weather_Sunny,hour,minute
count,77299.000000,77299.000000,77299.000000,7.729900e+04,77299.000000,77299.000000,77299.000000,77299.000000,77299.000000,77299.000000,77299.000000,77299.000000,77299.000000,77299.000000,77299.000000
mean,38649.000000,570.088151,48.101838,9.394238e-02,2.014334,0.344455,0.673256,16.404619,0.903375,0.050570,0.269395,0.099846,0.368879,9.101347,22.271310
std,22314.443566,349.199529,0.302438,1.421905e-01,0.904665,0.475193,0.469026,7.240083,0.295448,0.219119,0.443649,0.299797,0.482504,6.856045,16.853641
min,0.000000,0.000000,48.000000,6.245650e-07,1.000000,0.000000,0.000000,-14.935097,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,19324.500000,247.000000,48.000000,1.822723e-02,1.000000,0.000000,0.000000,11.624189,1.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000
50%,38649.000000,579.000000,48.000000,4.775994e-02,2.000000,0.000000,1.000000,16.382587,1.000000,0.000000,0.000000,0.000000,0.000000,8.000000,15.000000
75%,57973.500000,847.000000,48.000000,1.085951e-01,3.000000,1.000000,1.000000,21.115592,1.000000,0.000000,1.000000,0.000000,1.000000,14.000000,30.000000
max,77298.000000,1248.000000,49.000000,1.000000e+00,5.000000,1.000000,1.000000,48.251433,1.000000,1.000000,1.000000,1.000000,1.000000,23.000000,45.000000